# for spring-kafka clients (reactor-kafka)
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="MY_API_KEY" password="MY_API_SECRET";
spring.kafka.properties.client.dns.lookup=use_all_dns_ips

# for spring-cloud-stream binder (if used)
# spring.cloud.stream.kafka.binder.brokers=${CONFLUENT_BOOTSTRAP:pkc-921jm.us-east-2.aws.confluent.cloud:9092}
# spring.cloud.stream.kafka.binder.configuration.security.protocol=SASL_SSL
# spring.cloud.stream.kafka.binder.configuration.sasl.mechanism=PLAIN
# spring.cloud.stream.kafka.binder.configuration.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="MY_API_KEY" password="MY_API_SECRET";
# spring.cloud.stream.kafka.binder.configuration.client.dns.lookup=use_all_dns_ips

# spring.cloud.stream.kafka.binder.auto-create-topics=false
# spring.cloud.stream.kafka.binder.auto-add-partitions=false