spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CONFLUENT_API_KEY}" password="${CONFLUENT_API_SECRET}";
spring.kafka.properties.client.dns.lookup=use_all_dns_ips
spring.kafka.properties.ssl.endpoint.identification.algorithm=



# OpenTelemetry tracing configuration
management.tracing.sampling.probability=${TRACING_SAMPLING:1.0}

# Enable tracing
management.tracing.enabled=true

# OTLP trace collector endpoint
# management.tracing.export.otlp.endpoint=${OTLP_ENDPOINT:http://localhost:4318/v1/traces}

# HTTP Request SLO Metrics
# management.metrics.distribution.percentiles.http.server.requests=${HTTP_SERVER_REQ_PERCENTILES:0.5,0.9,0.95,0.99}
# management.metrics.distribution.slo.http.server.requests=${HTTP_SERVER_REQ_SLO:100ms,250ms,500ms,1s,2s}
